DROP TABLE pokemons IF EXISTS;

CREATE TABLE pokemons (
  pokemon_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_name VARCHAR(50),
  pokemon_url_image  VARCHAR(100),
  pokemon_type VARCHAR(50)
);